package se.lexicon.g4_jpa_assignment.Enum;

public enum Measurement {
    MEASUREMENT_TBSP, MEASUREMENT_TSP, MEASUREMENT_G, MEASUREMENT_HG, MEASUREMENT_KG, MEASUREMENT_ML, MEASUREMENT_CL, MEASUREMENT_DL

}
